In [1]:
import numpy as np

In [14]:
n = int(input('Введите N = '))
arr = np.arange(n-1, -1,-1)
arr

Введите N = 25


array([24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,
        7,  6,  5,  4,  3,  2,  1,  0])

In [20]:
n = int(input('Введите N = '))
arr = np.arange(0, n)
arr = arr[::-1]
matrix= np.diag(arr)
print(matrix_)
summa=np.trace(matrix)

print('Сумма значений матрицы по диагонали =', summa)

Введите N = 11
[[10  0  0  0  0  0  0  0  0  0  0]
 [ 0  9  0  0  0  0  0  0  0  0  0]
 [ 0  0  8  0  0  0  0  0  0  0  0]
 [ 0  0  0  7  0  0  0  0  0  0  0]
 [ 0  0  0  0  6  0  0  0  0  0  0]
 [ 0  0  0  0  0  5  0  0  0  0  0]
 [ 0  0  0  0  0  0  4  0  0  0  0]
 [ 0  0  0  0  0  0  0  3  0  0  0]
 [ 0  0  0  0  0  0  0  0  2  0  0]
 [ 0  0  0  0  0  0  0  0  0  1  0]
 [ 0  0  0  0  0  0  0  0  0  0  0]]
Сумма значений матрицы по диагонали = 55


In [21]:
from numpy import linalg

In [23]:
 # Решите систему уравнений:

# 4x + 2y + z = 4
# x + 3y = 12
# 5y + 4z = -3

In [24]:
a = np.array([[4,2,1],[1,3,0],[0,5,4]])
b = np.array([4,12,-3])
linalg.solve(a,b)

array([ 0.46666667,  3.84444444, -5.55555556])

In [32]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

In [38]:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

In [39]:
cosine_list = []

for i,vector in enumerate(users_stats):
    vector = users_stats[i]

    cosine_list.append(cosine( vector, next_user_stats ))
    
similar_user = cosine_list.index(max(cosine_list))

print(f"Самый похожий пользователь - №{similar_user+1}, его история покупок {users_stats[similar_user]} максимально совпадает с историей очередного посетителя {next_user_stats}, косинусное сходство {max(cosine_list)}")

Самый похожий пользователь - №8, его история покупок [0 1 1 0 0 0] максимально совпадает с историей очередного посетителя [0 1 2 0 0 0], косинусное сходство 0.9486832980505138
